Fix the connection timeout with dead webhook endpoints
RealDeviceMap/RealDeviceMap pull request #194
Opened 2021-02-17 16:20 UTC by Fabio1988

tried to fix the connection timeout with dead webhook endpoints

## Description
default timeout is now 30 seconds instead of 300. Can be configured in [docker-compose.yml](docker-compose.yml)

## Motivation and Context
related to issue #177 

## How Has This Been Tested?
Not tested.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-02-17 18:27 UTC, 123FLO321 requested changes

2021-02-17 18:27 UTC, 123FLO321 commented on Sources/RealDeviceMap/Controller/WebHookController.swift
> +        timeout = enviroment["WEBHOOK_ENDPOINT_CONNECT_TIMEOUT"] ?? 30
needs to be parsed as Int
```swift
 timeout = enviroment["WEBHOOK_ENDPOINT_CONNECT_TIMEOUT"]?.toInt() ?? 30
 ```

2021-03-01 17:49 UTC, Fabio1988 commented
have someone tested yet?

2021-03-13 16:58 UTC, tomhatzer commented on Sources/RealDeviceMap/Controller/WebHookController.swift
> +            .addHeader(.userAgent, "RealDeviceMap \(VersionManager.global.version)"),
@Fabio1988 do you need the `\` here or can it be removed? (or is there one missing at the end?) 😃

2021-03-22 15:22 UTC, Fabio1988 commented
Be careful @123FLO321 ... these changes are also in #204

2021-03-26 17:56 UTC, merged