Cell Pokemon Support
RealDeviceMap/RealDeviceMap pull request #208
Opened 2021-04-15 22:21 UTC by SkOODaT

## Description
Adds Basic Cell Pokemon Support, It Could Be Expanded Possibly.
No IVs, No GPS, Their The "Grass" Pokemon
Mons Should Update If Seen At A Stop Or IV-ed

## Motivation and Context
They Have Been There, In The Data, Why Not Show Them, Rurals Areas Could Benifit By This Type Of Scanning Alot....

## How Has This Been Tested?
Locally On My Own Map, With All Devices Going.

## Screenshots (if appropriate):
![CELL](https://user-images.githubusercontent.com/8633932/114945389-3c6aca00-9e17-11eb-8110-9dbbc595e683.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-04-15 22:43 UTC, wrinklytesties commented
My personal take on this PR, esp since these specific wild pokemon were discussed during the early RDM days (when plus plus first dropped mapper functions), and as a result of those discussion, these specific mons in the GMO were excluded for the following reasons:

- Pokes are anywhere up to 200m range of the center point of the jump
- There is no unique identifiable location data, requiring far too many jumps to discover the location
- There is no unique anchor (pokestop) that reduces the range to a less resource and time heavy task

With that said while low device coverage and rural areas could benefit heavily from discovery, if these find their way on the front end display, there will be confusion amongst users as where the actual poke is located.  With nearby pokemon anchored to pokestops, it is within a 70m distance, making discovery easy.

At 200m range with no anchor, you'd have to tie this into the center point of whatever jump first returned it.  For users, that's a 200m range of a location to discover what is there.  If a custom IV priority method is developed to IV these mons with no location, that's up to 6-8 jumps. 

For large setups, this will make the DB incredibly busy.   If this were to be merged, it would be nice if you can make this configurable in the YML file, allowing the host to enable/disable it on docker start up.  There is going to be so much noise from this PR for incredibly large setups.

2021-04-15 22:48 UTC, SkOODaT commented
well for a large setup a toggle could be added but this data is in the data being processed already its just not added to the database, as for users finding them, ive been using a pokemon type scheme on my front end since the beginning, i plan to possibly add to this PR... ie 
![Untidadadtled](https://user-images.githubusercontent.com/8633932/114947445-2e1ead00-9e1b-11eb-9f18-140c60689474.png)

2021-04-15 22:53 UTC, wrinklytesties commented
Yes, this will add additional inserts and updates.  So if you can make this configurable in the YML to be enabled/disabled, it will allow those with large setups to avoid this influx where the benefits are incredibly low for those type of setups.

Adding the configurable option, will make for easier performance testing as well.

2021-05-26 10:24 UTC, 123FLO321 requested changes
looks good, except some minor changes

2021-05-26 10:24 UTC, 123FLO321 commented on resources/webroot/index.js.mustache
>      if (pokemon.pokestop_id !== null && pokemon.spawn_id === null) {
wouldn't ` pokemon.spawn_id === null` cover both cases here?
Is there a reason for duplicating the code here?

2021-05-26 10:24 UTC, 123FLO321 commented on Sources/RealDeviceMap/Modell/Pokemon.swift
> +                let mysqlStmt = MySQLStmt(mysql)
why did the indentation change here and for the following lines?

2021-05-26 10:28 UTC, 123FLO321 commented
Also those pokemon should probably be excluded from IV checks because the exact location is hard to know:
(check if pokestopId and spawnId is null)
https://github.com/RealDeviceMap/RealDeviceMap/blob/6d5cab63ec629fc741d8c1b358cae264dfe22ff5/Sources/RealDeviceMap/Controller/InstanceControllers/IVInstanceController.swift#L170

2021-05-30 17:25 UTC, 123FLO321 commented
From my testing there are ~20% more spawns when using this PR.

2021-05-30 17:32 UTC, 123FLO321 commented
> Yes, this will add additional inserts and updates. So if you can make this configurable in the YML to be enabled/disabled, it will allow those with large setups to avoid this influx where the benefits are incredibly low for those type of setups.
> 
> Adding the configurable option, will make for easier performance testing as well.

Implemented via `NO_CELL_POKEMON` in 6e48209bcca0e50107840945f906c96a0e287257

2021-06-02 19:35 UTC, merged