ES Translations, localized hard-coded strings and other improvements.
RealDeviceMap/RealDeviceMap pull request #354
Opened 2022-05-16 18:05 UTC by Deses

I wanted to translate RDM to Spanish, and then I found out that there were many hard-coded string for the pop-ups and the stats page. Also, the date picker plugin wasn't using localizing so I added it.

## Description
--- Translations:
* Extracted all the hard-coded string from index.js to the lang files and replaced them with the respective i18n function.
* Updates EN and DE files with the new lines.
* New ES file with Spanish strings.
* Changed weathertypes,json into a new format that allows for localization.
* Added missing localizations to the stats page and made Flatpickr use the locale
--- Improvements:
* Forced initMap() to wait for all getJson() functions to complete before proceeding.
* Made popups with a minimal width to prevent elements overlapping.
* Changed popup logic to not process popups that are hidden. When shown again, they update correctly.
*

## Motivation and Context
### Why is this change required?
I wanted RDM in Spanish. :P

### What problem does it solve?
RDM did not have a Spanish translation and many strings were hard-coded.

### If it fixes an open issue, please link to the issue here.
No issue.

## How Has This Been Tested?
### Please describe in detail how you tested your changes.
Since I'm using docker, to test the changes I made to the .swift files, I cloned my fork, built it locally and uploaded a package to ghcr.io and then pulled it into my docker containers.

```
rdm:
    image: ghcr.io/deses/realdevicemap:translations
    ....
```

To quickly test the changes made in the js and lang files, I bound the webroot folder to a folder accesible to me and placed the files there. `- ./rdm:/app/resources/webroot/`

### Include details of your testing environment, and the tests you ran to
All ran in a Linux Mint 20.3 VM and then I just manually used RDM to see the changes.

### See how your change affects other areas of the code, etc.
It shouldn't affect anything!

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/1654959/168439073-1ecaddf0-7311-4cf3-af04-3f8d5a775ddc.png)
![image](https://user-images.githubusercontent.com/1654959/168655857-ac37ecb2-d65d-44fd-a294-d7c6fdd4a185.png)
![image](https://user-images.githubusercontent.com/1654959/168655973-8ddc6f82-a011-4b46-b144-6427a6f52bc5.png)
![image](https://user-images.githubusercontent.com/1654959/168656038-ed11ba95-be36-4b56-8ccd-1397fa029fb8.png)
![image](https://user-images.githubusercontent.com/1654959/168656092-758659b9-7faf-4a86-a509-95416fffef7e.png)
![image](https://user-images.githubusercontent.com/1654959/168656218-ccbef96b-6479-4688-928c-e264b665e06c.png)
![image](https://user-images.githubusercontent.com/1654959/168656302-186af524-5bdd-44dc-918e-d737ddde12e5.png)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-05-16 18:08 UTC, Deses commented
Since I made so many commits, I recommend you "squash and merge pr" rather than just merge it as to not pollute too much git's history. 😅

2022-05-17 11:26 UTC, Fabio1988 requested changes

2022-05-17 11:26 UTC, Fabio1988 commented on resources/webroot/index.js.mustache
>    content += '<span class="text-nowrap"><h6><b>{{#perm_admin}}<a href="#" onclick="editPokestopName(\''+pokestop.id+'\',\''+pokestop.name+'\')">{{/perm_admin}}' +
I think we can keep the old way for pokestop/gym name and remove `text-nowrap` for name. maybe use 2 cols for team icon and name :)

2022-05-18 08:22 UTC, Fabio1988 commented on resources/webroot/static/data/de.json
> +        "map_spawnpoint": "Spawnpunkte",
Spawnpunkt

2022-05-18 08:22 UTC, Fabio1988 commented on resources/webroot/static/data/de.json
> +        "map_spawnpoint": "Spawnpunkte",
Spawnpunkt

2022-05-18 08:23 UTC, Fabio1988 commented on resources/webroot/static/data/de.json
> +        "map_despawn_timer": "Spawn-Zeiten",
`"map_despawn_timer": "Despawn-Zeit"`

2022-05-18 08:23 UTC, Fabio1988 commented on resources/webroot/static/data/de.json
> +        "map_despawn_timer": "Spawn-Zeiten",
`"map_despawn_timer": "Despawn-Zeit"`

2022-05-18 12:49 UTC, Fabio1988 commented on resources/webroot/index.js.mustache
> +let popupPokemon
I think that is causing the direct link problems?! :+1:

2022-05-23 08:49 UTC, Fabio1988 approved these changes

2022-05-23 10:20 UTC, Fabio1988 approved these changes

2022-05-23 10:22 UTC, merged