MITM communication
RealDeviceMap/RealDeviceMap pull request #425
Opened 2022-10-17 14:55 UTC by Fabio1988

provide better error events on account fetching.

RDM should not return http 404 when account is not found, it should return 200 with proper error codes... needs testing with MITM.... I am in contact with devs.

2022-10-18 07:14 UTC, 123FLO321 commented
Does the api still respond with the correct http status code?

2022-10-18 07:16 UTC, Fabio1988 commented
> Does the api still respond with the correct http status code?

No, because none of the MITM can provide handling for 404.... It's a tricky workaround for them and mostly not handled.. some MITM even crash/restart on a 404.. I will write you a DM

2022-10-18 10:00 UTC, Fabio1988 commented
Or should we still use status codes like NOT_FOUND 404 with proper error in response?

2022-10-18 17:39 UTC, 123FLO321 requested changes

2022-10-18 17:39 UTC, 123FLO321 commented on Sources/RealDeviceMapLib/Webhook/WebHookRequestHandler.swift
> +                        response.respondWithError(event: .taskNotFound)
rename to `noTaskLeft`

2022-10-18 17:39 UTC, 123FLO321 commented on Sources/RealDeviceMapLib/Webhook/WebHookRequestHandler.swift
> +                        response.respondWithError(event: .accountNotFound)
rename to `noAccountLeft`

2022-10-18 17:40 UTC, 123FLO321 commented on Sources/RealDeviceMapLib/Webhook/WebHookRequestHandler.swift
> +                        response.respondWithError(event: .accountNotFound)
(only this occurrence. other occurrences can stay as `accountNotFound`)

2022-12-29 14:49 UTC, Fabio1988 commented
any more thoughts on that?

2023-03-31 22:03 UTC, merged

2023-03-31 22:05 UTC, Fabio1988 commented
Mentioned thousand times, time to merge